version: '3'
 
services:
  react:
      image: registry.digitalocean.com/min-blog-registry/react:latest
      build:
        context: ./frontend
        dockerfile: ./Dockerfile.production
      ports: 
       - '80:80'
      environment:
        - NGINX_PORT=80
      depends_on:
        - app

  app:
    image: registry.digitalocean.com/min-blog-registry/app:latest
    build:
      context: .
      dockerfile: ./Dockerfile.production
    ports:
      - "8000:8000"
    expose:
      - '8000'
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env.dev
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: