# Generated by Django 4.1.7 on 2023-03-06 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_myuser_reset_start_time_tweetreplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='reset_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 6, 6, 36, 22, 628734)),
        ),
        migrations.AlterField(
            model_name='tweetreplies',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tweetreplies'),
        ),
    ]
