# Generated by Django 4.1.7 on 2023-03-07 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_myuser_reset_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='reset_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 7, 2, 12, 17, 274141)),
        ),
    ]
