# Generated by Django 4.1.7 on 2023-03-21 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_myuser_reset_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='reset_start_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 21, 7, 25, 2, 34480)),
        ),
    ]
